### PR TITLE
Backend Features to support user registration

### PR DESCRIPTION
**Pull request by enbeec**
#### Changes Made

1. Added `users` module with `request.py` exporting `get_user_by_email` and `create_new_user`
2. Added `get_user_by_email` to `do_GET` in `request_handler.py`
3. Added `create_new_user` to `do_POST` in `request_handler.py`

#### Steps to Review

1. Checkout this branch locally.
   ```
   git fetch --all
   git checkout branchname
   ```
2. Ensure the backend is running
4. Test app functionality.
   > Manually get a user by email (GET `/users?email=steve@brownlee.com`)
   > Manually send a user to the database (POST `/users` with a user in the post body)
5. View code file.
   > Confirm file modifications are present as indicated above.
   > Confirm no unused code or extraneous comments exist.

### CODE REVIEW

**Comment by enbeec** [comment]
Enables completing: https://github.com/nss-day-cohort-48/rare-client-orchesta-outlaws/issues/1

**Comment by enbeec** [comment]
Also enables: https://github.com/nss-day-cohort-48/rare-client-orchesta-outlaws/issues/2

**Review by alambrow — APPROVED** [review]
Tested get_user_by_email and create_new_user in Postman. Both work!

**Review by mecrowley — APPROVED** [review]
Passes all tests.  File modifications are present as indicated above.

**Pull request merged**
